# Generated by Django 4.0.1 on 2022-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
