# Generated by Django 4.0.1 on 2022-01-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_accountmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
